#!/bin/bash -e

mkdir -p /storage

# We don't do it recursively, because it could be a lot of files.
chown -f meteor:meteor /storage /storage/publication /storage/publication/* /.meteorsession

export PATH=/.meteor/tools/latest/bin:$PATH
export NODE_PATH=/.meteor/tools/latest/lib/node_modules
export NODE_ENV='production'
export STORAGE_DIRECTORY='/storage'

# You can mount a volume (file) into this location to provide a script which sets environment variables.
[ -f /etc/service/meteor/run.config ] && source /etc/service/meteor/run.config

cd /bundle/programs/server/npm/mongo
cat /etc/service/meteor/wait_db.js | node

# Initialization hook.
[ -f /etc/service/meteor/run.initialization ] && source /etc/service/meteor/run.initialization

cd /bundle
exec chpst -u meteor:meteor node --stack-trace-limit=1000 main.js 2>&1
