#!/bin/bash -e

mkdir -p "$STORAGE_DIRECTORY"
chown -Rhf peerlibrary:peerlibrary "$STORAGE_DIRECTORY" /.meteorsession

export PATH=/.meteor/tools/latest/bin:$PATH
export NODE_PATH=/.meteor/tools/latest/lib/node_modules
export NODE_ENV='PRODUCTION'

cd /bundle
exec chpst -u peerlibrary:peerlibrary node main.js 2>&1
